In [9]:
import numpy as np

# Define custom numpy arrays A and B
A = np.array([5, 6, 7, 8])
B = np.array([9, 8, 7, 6])

# Stack arrays A and B vertically
vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

# Stack arrays A and B horizontally
horizontal_stack = np.hstack((A, B))
print("Horizontal Stack:", horizontal_stack)

# Extract numbers from A that are between 5 and 10
extracted_values = A[(A > 5) & (A < 10)]
print("Extracted Values between 5 and 10:", extracted_values)

Vertical Stack:
 [[5 6 7 8]
 [9 8 7 6]]
Horizontal Stack: [5 6 7 8 9 8 7 6]
Extracted Values between 5 and 10: [6 7 8]


In [10]:
# Find common elements between A and B using intersection
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [6 7 8]


In [11]:
# Extract numbers from A that are between 5 and 10
extracted_values = A[(A > 5) & (A < 10)]
print("Extracted Values between 5 and 10:", extracted_values)

Extracted Values between 5 and 10: [6 7 8]


In [12]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filter rows where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)

Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [13]:
import pandas as pd

url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

# Filter 'Manufacturer', 'Model', and 'Type' for every 20th row starting from the 1st (index 0)
filtered_df = df[['Manufacturer', 'Model', 'Type']].iloc[::20]
print("Filtered Data:\n", filtered_df)

Filtered Data:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [18]:
# Replace missing values in Min.Price and Max.Price with their mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print("Data after replacing missing values:\n", df[['Min.Price', 'Max.Price']].head())

KeyError: 'Min.Price'

In [15]:
import numpy as np
import pandas as pd

# Create a random dataframe
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Find rows where the sum is greater than 100
rows_with_sum_greater_than_100 = df[df.sum(axis=1) > 100]
print("Rows with sum greater than 100:\n", rows_with_sum_greater_than_100)

Rows with sum greater than 100:
      0   1   2   3
1   33  37  29  36
2   17  38  14  34
4   37  24  35  15
12  35  18  35  15
13  31  32  27  39
