In [20]:
import numpy as np

# Define custom numpy arrays A and B
A = np.array([5, 6, 7, 8])
B = np.array([9, 8, 7, 6])

# Stack arrays A and B vertically
vertical_stack = np.vstack((A, B))
print("Vertical Stack:\n", vertical_stack)

# Stack arrays A and B horizontally
horizontal_stack = np.hstack((A, B))
print("Horizontal Stack:", horizontal_stack)

# Extract numbers from A that are between 5 and 10
extracted_values = A[(A > 5) & (A < 10)]
print("Extracted Values between 5 and 10:", extracted_values)

Vertical Stack:
 [[5 6 7 8]
 [9 8 7 6]]
Horizontal Stack: [5 6 7 8 9 8 7 6]
Extracted Values between 5 and 10: [6 7 8]


In [21]:
# Find common elements between A and B using intersection
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [6 7 8]


In [22]:
# Extract numbers from A that are between 5 and 10
extracted_values = A[(A > 5) & (A < 10)]
print("Extracted Values between 5 and 10:", extracted_values)

Extracted Values between 5 and 10: [6 7 8]


In [23]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filter rows where petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)

Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [24]:
import pandas as pd

url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

# Filter 'Manufacturer', 'Model', and 'Type' for every 20th row starting from the 1st (index 0)
filtered_df = df[['Manufacturer', 'Model', 'Type']].iloc[::20]
print("Filtered Data:\n", filtered_df)

Filtered Data:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [25]:
import pandas as pd

url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

# Replace missing values in Min.Price and Max.Price with their mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print("Data after replacing missing values:\n", df[['Min.Price', 'Max.Price']].head())

Data after replacing missing values:
    Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


/tmp/ipykernel_414/2688482540.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/tmp/ipykernel_414/2688482540.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=Tr

In [26]:
import numpy as np
import pandas as pd

# Create a random dataframe
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Find rows where the sum is greater than 100
rows_with_sum_greater_than_100 = df[df.sum(axis=1) > 100]
print("Rows with sum greater than 100:\n", rows_with_sum_greater_than_100)

Rows with sum greater than 100:
      0   1   2   3
1   27  26  37  33
2   39  23  34  33
3   39  24  20  27
5   27  29  10  38
6   34  24  12  37
8   35  30  22  20
12  17  28  32  33
13  37  19  33  24
